"$schema" = "https://starship.rs/config-schema.json"

add_newline = true
continuation_prompt = "[▸▹ ](dimmed white)"

format = """$username$hostname $directory $character"""
right_format = "$git_branch$git_status$cmd_duration"

[username]
format = '[\[](fg:#2883ff)[$user]($style)[@](fg:#2883ff)'
show_always = true
style_user = 'fg:#2883ff'
style_root = 'fg:#2883ff bold'
[hostname]
disabled = false
format = '[$hostname]($style)[\]](fg:#2883ff)'
ssh_only = false
style = 'fg:#2883ff'

[directory]
format = '[$path]($style)'
style = 'bold fg:blue'
truncate_to_repo = false
truncation_length = 3
truncation_symbol = '…/'

[character]
error_symbol = '[\$](bold red)'
vimcmd_symbol = '[\$](bold blue)'
success_symbol = '[\$](bold green)'

[git_branch]
format = '[\[$branch]($style)'
style = 'bold fg:blue'
[git_status]
format = '[|$all_status$ahead_behind\]]($style)'
style = 'bold fg:blue'

ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'

[cmd_duration]
format = ' [$duration]($style)'
min_time = 0
style = 'fg:gray'
