"$schema" = "https://starship.rs/config-schema.json"

# format = """$username$hostname $directory $character"""
# right_format = "$git_branch$git_status$cmd_duration"

# Customizing the prompt (and placing desired modules at desired position and sequence):
# ╭╴ # \u256D\u2574
# ╰╴ # \u2570\u2574

add_newline = true
format = """
[\u256D\u2574](fg:greydimmed)\
$sudo\
$directory\
[ ](fg:greydimmed)\
$fill\
$username\
$hostname\
[ ](fg:greydimmed)\
$fill\
$git_branch$git_status \
$status\
$cmd_duration\
$line_break\
\
[\u2570\u2574](fg:greydimmed)\
$character"""


[username]
format = '[\[](fg:greydimmed)[$user]($style)[@](fg:greydimmed)'
show_always = true
style_user = 'fg:#2883ff'
style_root = 'fg:red'

[hostname]
disabled = false
format = '[$hostname]($style)[\]](fg:greydimmed)'
ssh_only = false
style = 'fg:#2883ff'

[directory]
format = '[$path]($style)'
style = 'bold fg:blue'
truncate_to_repo = false
truncation_length = 3
truncation_symbol = '…/'

[character]
error_symbol = '[\$](bold red)'
vimcmd_symbol = '[\$](bold blue)'
success_symbol = '[\$](bold green)'

[git_branch]
format = '[\[](fg:greydimmed)[$branch]($style)'
style = 'bold fg:blue'
[git_status]
format = '[|](fg:greydimmed)[$all_status$ahead_behind]($style)[\]](fg:greydimmed)'
style = 'bold fg:blue'

ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'

[cmd_duration]
format = ' [$duration]($style)'
min_time = 0
style = 'fg:greydimmed'
